### PR TITLE
Add destructure structs feature

### LINKED ISSUE #2: Destructure Structures
```
defmodule Foo do
  defstruct bar: 0

  import Destructure

  def take_foo(d%Foo{bar}) do
    :ok
  end
end
```

This fails to compile. I would like it to compile, and have `bar` in scope in `take_foo/1`.

### PR DESCRIPTION
**Pull request by chouzan**
Closes #2.

### CODE REVIEW

**Comment by chouzan** [comment]
Need help beforehand, @danielberkompas how to move the test do doctest for this case? I try to move the module definition for `Person` but no luck. Seems like the module definition in doctest doesn't reference the module in the test namespace, and use the lib namespace instead.

**Comment by danielberkompas** [comment]
@muhifauzan Try this?

```elixir
defmodule DestructureTest do
  use ExUnit.Case

  import Destructure

  defmodule Person do
    defstruct [:name, :email]
  end

  doctest Destructure

  test "destructure a simple structs" do
    d(%Person{name}) = %Person{name: "Joe"}
    assert name == "Joe"
  end

  test "destructure a simple struct with custom variable naming" do
    d(%Person{name, email: mail}) = %Person{name: "Joe", email: "email@example.com"}
    assert {name, mail} == {"Joe", "email@example.com"}
  end
end
```

Defining the `Person` module above the doctest call should make it available in doctests.

**Comment by chouzan** [comment]
Ah, I see. I'll try to implement that later.

**Comment by chouzan** [comment]
@danielberkompas please have a look.

**Comment by danielberkompas** [comment]
Looks great! Thanks! :star:

**Comment by Havvy** [comment]
Thanks!

**Comment by chouzan** [comment]
Anytime 😄

**Pull request merged**
